apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-cpi.community.tanzu.vmware.com.1.22.5
spec:
  refName: vsphere-cpi.community.tanzu.vmware.com
  version: 1.22.5
  releaseNotes: "vsphere-cpi 1.22.5 https://github.com/kubernetes/cloud-provider-vsphere"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-cpi@sha256:dc1122cf67571fbbda28bceaeba05284af14004b72088d1418c1dd75ce555f0a
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
